# Generated by Django 4.2.16 on 2024-11-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('WD', 'Web Development'), ('DT', 'Descktop Development'), ('DS', 'Data Science')], default='WD', max_length=50),
        ),
    ]
